/**
 * OpenAPI facade: the generator-independent core (docs/nx-umsetzung.md → "OpenAPI-Clients").
 *
 *   spec.file (committed) ──adapter.generate──▶ tmp/openapi/<path>/raw ──adapter.classify──▶ models/apis/core
 *     ──splitIntoParts──▶ <client>/{types,api,core}/src/generated/** (gitignored) + generated/index.ts
 *
 * The facade owns placement, split, import rewriting and the lint header; the adapter only raw
 * output + classification. Contract: contract.ts.
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { listTsFiles } from './adapters/files';
import { ADAPTER_MODULES } from './adapters/index';
import { buildBarrel } from './barrel';
import type { AdapterRegistration, ClientDefinition, GenerateContext, GeneratorAdapter, Part } from './contract';
import { splitIntoParts } from './split';

// __dirname: the package has no "type": "module", Nx loads its .ts sources as CommonJS (swc)
const registry = JSON.parse(readFileSync(join(__dirname, 'adapters/registry.json'), 'utf-8')) as Record<
  string,
  AdapterRegistration
>;

export const PARTS: readonly Part[] = ['types', 'api', 'core'];
/** gitignored subfolder of every client lib; the committed src/index.ts re-exports it */
export const GENERATED_DIR = 'generated';

type ClientLocation = Pick<ClientDefinition, 'name' | 'placement'>;

export const clientRoot = (client: ClientLocation): string =>
  client.placement === 'shared'
    ? `libs/generated/${client.name}`
    : `libs/${client.placement.domain}/generated/${client.name}`;
export const partRoot = (client: ClientLocation, part: Part): string => `${clientRoot(client)}/${part}`;
export const partAlias = (client: ClientLocation, part: Part): string =>
  `@mo-transfer/${partRoot(client, part).slice('libs/'.length)}`;

/**
 * Lint on generated code: everything off, only the boundary rules on. So tags (types → api
 * forbidden) and the deep-import ban still apply to generated files.
 */
export const generatedHeader = (source: string, specFile: string): string =>
  [
    '/* eslint-disable */',
    '/* eslint-enable @nx/enforce-module-boundaries, no-restricted-imports */',
    `// Generated by @mo-transfer/tooling (openapi, ${source}) from ${specFile}. Do not edit, do not commit.`,
    '',
  ].join('\n');

interface ClientsJson {
  defaultAdapter?: string;
  clients?: Record<string, { url?: string; adapter?: string; options?: Record<string, unknown> }>;
}

/**
 * ClientDefinition of `clientPath` (below libs/) from openapi-clients.json + the client folder — read at run
 * time by the executors (their options are only `{ client }`, so the entry never enters the project config).
 */
export function resolveClient(workspaceRoot: string, clientPath: string): ClientDefinition {
  const config = JSON.parse(readFileSync(join(workspaceRoot, 'openapi-clients.json'), 'utf-8')) as ClientsJson;
  const entry = config.clients?.[clientPath];
  if (!entry) throw new Error(`openapi-clients.json has no entry "${clientPath}"`);
  const segments = clientPath.split('/');
  const placement = segments[0] === 'generated' ? 'shared' : { domain: segments[0] };
  const specs = ['openapi.yaml', 'openapi.json'].filter((file) =>
    existsSync(join(workspaceRoot, 'libs', clientPath, file)),
  );
  if (specs.length !== 1) throw new Error(`libs/${clientPath}: needs exactly one spec (openapi.yaml | openapi.json)`);
  return {
    name: segments.at(-1) as string,
    placement,
    spec: { file: `libs/${clientPath}/${specs[0]}`, ...(entry.url ? { url: entry.url } : {}) },
    generator: { adapter: entry.adapter ?? config.defaultAdapter ?? 'openapi-tools', options: entry.options ?? {} },
  };
}

/** Adapter of a registry id: its module (registry.json → module, see adapters/index.ts) + defaults. */
export async function loadAdapter(
  id: string,
): Promise<{ adapter: GeneratorAdapter; defaults: Record<string, unknown> }> {
  const registration = registry[id];
  if (!registration || id.startsWith('$')) {
    throw new Error(
      `Unknown adapter '${id}'. Known: ${Object.keys(registry)
        .filter((key) => !key.startsWith('$'))
        .join(', ')}`,
    );
  }
  const module = ADAPTER_MODULES[registration.module];
  if (!module) throw new Error(`Adapter '${id}': module ${registration.module} not listed in adapters/index.ts`);
  return { adapter: module.default, defaults: module.defaults ?? {} };
}

export async function generateClient(
  client: ClientDefinition,
  workspaceRoot: string,
): Promise<Partial<Record<Part, number>>> {
  const specFile = join(workspaceRoot, client.spec.file);
  if (!existsSync(specFile))
    throw new Error(`${client.spec.file} missing (spec.url set? → nx run <client>:update-spec)`);
  const { adapter, defaults } = await loadAdapter(client.generator.adapter);
  const outDir = join(workspaceRoot, 'tmp/openapi', clientRoot(client).slice('libs/'.length), 'raw');
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const context: GenerateContext = {
    specFile,
    outDir,
    options: { ...defaults, ...client.generator.options },
    workspaceRoot,
    client,
  };
  await adapter.generate(context);
  const classification = await adapter.classify(context);

  const aliases = Object.fromEntries(PARTS.map((part) => [part, partAlias(client, part)])) as Record<Part, string>;
  const parts = splitIntoParts({ rawDir: outDir, classification, aliases, allFiles: listTsFiles(outDir) });
  const header = generatedHeader(`adapter ${client.generator.adapter}`, client.spec.file);

  const written: Partial<Record<Part, number>> = {};
  for (const part of PARTS) {
    const { files, entries } = parts[part];
    const libRoot = join(workspaceRoot, partRoot(client, part));
    const hasLib = existsSync(join(libRoot, 'src/index.ts'));
    if (!hasLib && files.length) {
      throw new Error(
        `${partRoot(client, part)}/src/index.ts missing, the adapter delivers ${files.length} files for it. ` +
          `Commit: echo "export * from './${GENERATED_DIR}';" > ${partRoot(client, part)}/src/index.ts`,
      );
    }
    if (!hasLib) continue;
    const targetDir = join(libRoot, 'src', GENERATED_DIR);
    rmSync(targetDir, { recursive: true, force: true });
    for (const { path, content } of files) {
      const target = join(targetDir, path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, header + content);
    }
    const barrel = buildBarrel(outDir, entries);
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(join(targetDir, 'index.ts'), `${header}${barrel}\n`);
    written[part] = files.length;
  }
  return written;
}

/**
 * Normalized spec text: YAML (with a source comment) or JSON, chosen by the file extension, then
 * Prettier with the workspace config — the same result the generators' formatFiles produce, so
 * `update-spec` right after `nx g …:client` reports "unchanged".
 */
export async function serializeSpec(
  document: unknown,
  file: string,
  url: string,
  projectName: string,
  workspaceRoot: string,
): Promise<string> {
  const text = file.endsWith('.json')
    ? `${JSON.stringify(document, null, 2)}\n`
    : [
        `# Source: ${url}`,
        `# Update: nx run ${projectName}:update-spec (overwrites this file, normalized). Committed, the only source for generate-api-client.`,
        stringifyYaml(document, { lineWidth: 0, aliasDuplicateObjects: false }),
      ].join('\n');
  const prettier = await import('prettier').catch(() => undefined);
  if (!prettier) return text;
  const filepath = join(workspaceRoot, file);
  const options = (await prettier.resolveConfig(filepath, { editorconfig: true })) ?? {};
  return prettier.format(text, { ...options, filepath });
}

/**
 * Downloads the spec from spec.url (JSON or YAML) and writes it normalized to spec.file.
 * The file stays the only source for generate-api-client (cache input); nothing is generated from the URL.
 */
export async function updateSpec(
  client: ClientDefinition,
  workspaceRoot: string,
  projectName: string,
): Promise<{ changed: boolean }> {
  if (!client.spec.url) throw new Error(`${client.name}: no url (openapi-clients.json → clients → <path> → url)`);
  const response = await fetch(client.spec.url);
  if (!response.ok) throw new Error(`GET ${client.spec.url}: ${response.status}`);
  const document: unknown = parseYaml(await response.text());
  const normalized = await serializeSpec(document, client.spec.file, client.spec.url, projectName, workspaceRoot);
  const file = join(workspaceRoot, client.spec.file);
  const before = existsSync(file) ? readFileSync(file, 'utf-8') : undefined;
  if (before !== normalized) writeFileSync(file, normalized);
  return { changed: before !== normalized };
}
