/**
 * Testing preset (openapi-typescript, openapi-msw + a mocks engine: none (default: typed http only, no fake data),
 * schema-faker or orval (deprecated)) from the fixture spec, and the generated handlers really answering through
 * msw 3 in Node (setupServer) with data shaped by the spec — the same assertions for both faking engines.
 */
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { ClientDefinition } from '../../src/adapter';
import { generateTesting, resolveClient } from '../../src/facade';
import { camelCase } from '../../src/settings';

const generateTestingLib = (client: ClientDefinition, root: string) => generateTesting(client, root, {}, {});
import {
  addClient,
  createWorkspace,
  filesBelow,
  fixture,
  hashTree,
  read,
  removeWorkspace,
  THINGS_SPEC,
  typecheck,
} from '../helpers';

const HEADER_START =
  '/* eslint-disable */\n/* eslint-enable @nx/enforce-module-boundaries, no-restricted-imports */\n// Generated by @mo-transfer/tooling (openapi, testing)';

describe('testing lib generation, mocks: orval (deprecated)', () => {
  let root: string;
  const clientPath = 'generated/things-client';
  const generatedDir = () => join(root, 'libs', clientPath, 'testing/src/generated');
  let result: { baseUrl: string; files: number };

  beforeAll(async () => {
    root = createWorkspace('testing');
    addClient(root, clientPath, { entry: { pipeline: { testing: { mocks: 'orval' } } } });
    result = await generateTestingLib(resolveClient(root, clientPath), root);
  });
  afterAll(() => removeWorkspace(root));

  it('writes schema, mocks, model, typed http, default handlers and a barrel — all with the header', () => {
    const files = filesBelow(generatedDir());
    expect(files).toEqual(expect.arrayContaining(['schema.ts', 'mocks.ts', 'http.ts', 'handlers.ts', 'index.ts']));
    expect(files.some((file) => file.startsWith('model/'))).toBe(true);
    expect(result).toEqual({ baseUrl: 'http://api.test/v1', files: files.length });
    for (const file of files) expect(read(generatedDir(), file).startsWith(HEADER_START)).toBe(true);
    expect(read(generatedDir(), 'http.ts')).toContain('export const thingsClientBaseUrl = "http://api.test/v1";');
    expect(read(generatedDir(), 'handlers.ts')).toContain(
      'export const thingsClientHandlers: HttpHandler[] = getThingsAPIMock();',
    );
  });

  it('is deterministic and compiles', async () => {
    const before = hashTree(generatedDir());
    await generateTestingLib(resolveClient(root, clientPath), root);
    expect(hashTree(generatedDir())).toEqual(before);
    expect(typecheck(root, [`libs/${clientPath}/testing/src/index.ts`])).toEqual([]);
  });

  it('the generated handlers answer through msw (Node) with data shaped by the spec', async () => {
    const { setupServer } = await import('msw/node');
    const testing = await import(pathToFileURL(join(generatedDir(), 'index.ts')).href);
    const server = setupServer(...testing.thingsClientHandlers);
    server.listen({ onUnhandledFrame: 'error' });
    try {
      // response example of the spec
      const things = await (await fetch('http://api.test/v1/things')).json();
      expect(things).toEqual([{ id: 't-1', name: 'Lamp', kind: 'tool', owner: { id: 'o-1', name: 'Ada' } }]);
      // no example: faker fills the schema (required props, enum, property examples)
      const thing = (await (await fetch('http://api.test/v1/things/t-9')).json()) as { kind: string };
      expect(thing).toMatchObject({ id: 't-1', name: 'Lamp' });
      expect(['tool', 'toy']).toContain(thing.kind);
      const owners = (await (await fetch('http://api.test/v1/owners')).json()) as unknown[];
      expect(Array.isArray(owners)).toBe(true);
      for (const owner of owners) expect(owner).toEqual({ id: 'o-1', name: 'Ada' });

      // typed openapi-msw http overrides a default handler per test
      type Resolver = (info: {
        params: { id: string };
        response: (status: number) => { json: (body: object) => Response };
      }) => Response;
      const http = testing.thingsClientHttp as { get: (path: string, resolver: Resolver) => never };
      server.use(
        http.get('/things/{id}', ({ params, response }) =>
          response(200).json({ id: params.id, name: 'Override', kind: 'toy' }),
        ),
      );
      expect(await (await fetch('http://api.test/v1/things/x-1')).json()).toEqual({
        id: 'x-1',
        name: 'Override',
        kind: 'toy',
      });
    } finally {
      server.close();
    }
  });

  it('camelCase: client name → export prefix', () => {
    expect(camelCase('pet-client')).toBe('petClient');
    expect(camelCase('a-b2-c')).toBe('aB2C');
  });
});

describe('testing lib generation, mocks: none (library default: scaffold only, no fake data)', () => {
  let root: string;
  const clientPath = 'generated/things-client';
  const generatedDir = () => join(root, 'libs', clientPath, 'testing/src/generated');

  beforeAll(() => {
    root = createWorkspace('testing-none');
    addClient(root, clientPath);
  });
  afterAll(() => removeWorkspace(root));

  it('writes only schema, typed http and the barrel — no mocks, no handlers, no runtime copy, no faker', async () => {
    const result = await generateTestingLib(resolveClient(root, clientPath), root);
    const files = filesBelow(generatedDir());
    expect(files).toEqual(['http.ts', 'index.ts', 'schema.ts']);
    expect(result).toEqual({ baseUrl: 'http://api.test/v1', files: 3 });
    for (const file of files) {
      expect(read(generatedDir(), file).startsWith(HEADER_START)).toBe(true);
      expect(read(generatedDir(), file)).not.toMatch(/faker|MockHandler|ResponseMock|Handlers/);
    }
    expect(read(generatedDir(), 'http.ts')).toContain('export const thingsClientHttp = createOpenApiHttp<paths>');
    expect(read(generatedDir(), 'index.ts')).toContain("export * from './http';");
  });

  it('is deterministic and compiles', async () => {
    const before = hashTree(generatedDir());
    await generateTestingLib(resolveClient(root, clientPath), root);
    expect(hashTree(generatedDir())).toEqual(before);
    expect(typecheck(root, [`libs/${clientPath}/testing/src/index.ts`])).toEqual([]);
  });

  it('the typed http serves hand-written data through msw (Node)', async () => {
    const { setupServer } = await import('msw/node');
    const testing = await import(pathToFileURL(join(generatedDir(), 'index.ts')).href);
    expect(Object.keys(testing).sort()).toEqual(['thingsClientBaseUrl', 'thingsClientHttp']);
    type Resolver = (info: { response: (status: number) => { json: (body: object) => Response } }) => Response;
    const http = testing.thingsClientHttp as { get: (path: string, resolver: Resolver) => never };
    const server = setupServer(
      http.get('/owners', ({ response }) => response(200).json([{ id: 'o-7', name: 'Grace' }])),
    );
    server.listen({ onUnhandledFrame: 'error' });
    try {
      expect(await (await fetch('http://api.test/v1/owners')).json()).toEqual([{ id: 'o-7', name: 'Grace' }]);
    } finally {
      server.close();
    }
  });

  it('a spec without operations is fine (nothing to mock)', async () => {
    addClient(root, 'generated/empty-client', {
      spec: 'openapi: 3.0.3\ninfo: { title: Empty, version: 1.0.0 }\npaths: {}\n',
    });
    await expect(generateTestingLib(resolveClient(root, 'generated/empty-client'), root)).resolves.toMatchObject({
      files: 3,
    });
  });
});

describe('testing lib generation, mocks: schema-faker (opt-in, no orval)', () => {
  let root: string;
  const clientPath = 'generated/things-client';
  const generatedDir = () => join(root, 'libs', clientPath, 'testing/src/generated');
  const generateSchemaFaker = () => generateTestingLib(resolveClient(root, clientPath), root);

  beforeAll(() => {
    root = createWorkspace('testing-schema-faker');
    addClient(root, clientPath, { entry: { pipeline: { testing: { mocks: 'schema-faker' } } } });
  });
  afterAll(() => removeWorkspace(root));

  it('writes schema, runtime, mocks, model, http, handlers, index — no orval model/**', async () => {
    const result = await generateSchemaFaker();
    const files = filesBelow(generatedDir());
    expect(files.sort()).toEqual([
      'handlers.ts',
      'http.ts',
      'index.ts',
      'mock-runtime.ts',
      'mocks.ts',
      'model.ts',
      'schema.ts',
    ]);
    expect(result).toEqual({ baseUrl: 'http://api.test/v1', files: 7 });
    for (const file of files) expect(read(generatedDir(), file).startsWith(HEADER_START)).toBe(true);
    expect(read(generatedDir(), 'handlers.ts')).toContain('export const thingsClientHandlers: HttpHandler[] = [');
    // browser-safe runtime: only msw + a private faker instance (never the global `faker`)
    expect(read(generatedDir(), 'mock-runtime.ts').match(/^import .* from '([^']+)';$/gm)).toEqual([
      "import { base, en, Faker, generateMersenne53Randomizer } from '@faker-js/faker';",
      "import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions } from 'msw';",
    ]);
  });

  it('is deterministic and compiles', async () => {
    const before = hashTree(generatedDir());
    await generateSchemaFaker();
    expect(hashTree(generatedDir())).toEqual(before);
    expect(typecheck(root, [`libs/${clientPath}/testing/src/index.ts`])).toEqual([]);
  });

  it('the handlers answer like orval: spec examples, faker for the rest — same data per request, no seed', async () => {
    const { setupServer } = await import('msw/node');
    const { faker } = await import('@faker-js/faker');
    const testing = await import(pathToFileURL(join(generatedDir(), 'index.ts')).href);
    const server = setupServer(...testing.thingsClientHandlers);
    server.listen({ onUnhandledFrame: 'error' });
    try {
      const things = await (await fetch('http://api.test/v1/things')).json();
      expect(things).toEqual([{ id: 't-1', name: 'Lamp', kind: 'tool', owner: { id: 'o-1', name: 'Ada' } }]);
      const thing = (await (await fetch('http://api.test/v1/things/t-9')).json()) as { kind: string };
      expect(thing).toMatchObject({ id: 't-1', name: 'Lamp' });
      expect(['tool', 'toy']).toContain(thing.kind);
      faker.seed(7); // the global faker state does not matter
      faker.number.int();
      expect(await (await fetch('http://api.test/v1/things/t-9')).json()).toEqual(thing);
      // factory = handler data: assert on get<Op>ResponseMock()
      expect(testing.getGetThingResponseMock()).toEqual(thing);
      const owners = (await (await fetch('http://api.test/v1/owners')).json()) as unknown[];
      expect(owners.length).toBeGreaterThan(0);
      for (const owner of owners) expect(owner).toEqual({ id: 'o-1', name: 'Ada' });
      // orval-compatible factories + handler overrides
      expect(testing.getGetThingResponseMock({ name: 'X' })).toMatchObject({ id: 't-1', name: 'X' });
      server.use(testing.getListOwnersMockHandler([{ id: 'o-9', name: 'Grace' }]));
      expect(await (await fetch('http://api.test/v1/owners')).json()).toEqual([{ id: 'o-9', name: 'Grace' }]);
    } finally {
      server.close();
    }
  });

  it('values change only with the relevant part of the spec (fixture regenerated with unrelated changes)', async () => {
    type Spec = { paths: Record<string, unknown>; components: { schemas: Record<string, Record<string, unknown>> } };
    const variant = async (path: string, change: (spec: Spec) => void) => {
      const spec = parseYaml(THINGS_SPEC) as Spec;
      const thing = spec.components.schemas.Thing as { required: string[]; properties: Record<string, unknown> };
      // faker-driven fields (no examples), the subject of the comparison
      thing.properties.serial = { type: 'string', format: 'uuid' };
      thing.properties.madeAt = { type: 'string', format: 'date-time' };
      thing.properties.parts = { type: 'array', items: { type: 'integer', minimum: 1 } };
      thing.required.push('serial', 'madeAt', 'parts');
      change(spec);
      addClient(root, path, { spec: stringifyYaml(spec), entry: { pipeline: { testing: { mocks: 'schema-faker' } } } });
      await generateTestingLib(resolveClient(root, path), root);
      return import(pathToFileURL(join(root, 'libs', path, 'testing/src/generated/index.ts')).href);
    };
    const before = await variant('generated/before-client', () => undefined);
    const after = await variant('generated/after-client', (spec) => {
      const thing = spec.components.schemas.Thing as { properties: Record<string, unknown> };
      thing.properties = Object.fromEntries(Object.entries(thing.properties).reverse()); // reordered
      thing.properties.weight = { type: 'number', description: 'new, unrelated' }; // optional property added
      spec.components.schemas.Extra = { type: 'object', properties: { x: { type: 'string' } } }; // schema added
      spec.paths['/extras'] = {
        get: {
          operationId: 'listExtras',
          responses: {
            '200': {
              description: 'OK',
              content: { 'application/json': { schema: { $ref: '#/components/schemas/Extra' } } },
            },
          },
        },
      }; // operation added
      spec.components.schemas.Owner.description = 'docs only'; // doc change
    });
    const withoutWeight = ({ weight: _weight, ...rest }: Record<string, unknown>) => rest;
    const thing = before.getGetThingResponseMock();
    expect(thing.serial).toMatch(/^[0-9a-f-]{36}$/);
    expect(Date.parse(thing.madeAt)).toBeLessThan(Date.parse('2026-01-01T00:00:00.000Z'));
    expect(withoutWeight(after.getGetThingResponseMock())).toEqual(thing);
    expect(after.getListOwnersResponseMock()).toEqual(before.getListOwnersResponseMock());
    // call order and repetition do not matter
    after.getListExtrasResponseMock();
    expect(withoutWeight(after.getGetThingResponseMock())).toEqual(withoutWeight(after.getGetThingResponseMock()));
    // its own schema changes → only that field changes
    const changed = await variant('generated/changed-client', (spec) => {
      const thing = spec.components.schemas.Thing as { properties: Record<string, Record<string, unknown>> };
      thing.properties.parts.items = { type: 'integer', minimum: 1, maximum: 9 };
    });
    const { parts, ...others } = changed.getGetThingResponseMock();
    const { parts: partsBefore, ...othersBefore } = thing;
    expect(parts).toHaveLength(partsBefore.length); // the array's own schema is unchanged
    expect(parts).not.toEqual(partsBefore);
    expect(others).toEqual(othersBefore);
  });

  it('an unknown mocks engine fails with a hint', async () => {
    addClient(root, 'generated/odd-client', { entry: { pipeline: { testing: { mocks: 'nope' } } } });
    await expect(generateTestingLib(resolveClient(root, 'generated/odd-client'), root)).rejects.toMatchObject({
      message: 'unknown mocks engine "nope" (none | schema-faker | orval)',
    });
  });
});

describe('testing lib generation: errors', () => {
  let root: string;
  beforeAll(() => {
    root = createWorkspace('testing-errors');
  });
  afterAll(() => removeWorkspace(root));

  it('fails without spec file', async () => {
    const client: ClientDefinition = {
      name: 'x-client',
      path: 'generated/x-client',
      placement: 'shared',
      spec: { file: 'libs/generated/x-client/openapi.yaml' },
      generator: { adapter: 'openapi-tools', options: {} },
      layout: 'default',
      pipeline: {},
    };
    await expect(generateTestingLib(client, root)).rejects.toThrow('libs/generated/x-client/openapi.yaml missing');
  });

  it('fails without the committed testing index.ts', async () => {
    addClient(root, 'generated/no-testing-client', { parts: ['types', 'api', 'core'] });
    await expect(generateTestingLib(resolveClient(root, 'generated/no-testing-client'), root)).rejects.toThrow(
      "testing/src/index.ts missing (export * from './generated';)",
    );
  });

  it('fails for a spec without operations (both faking engines)', async () => {
    addClient(root, 'generated/empty-client', {
      spec: 'openapi: 3.0.3\ninfo: { title: Empty, version: 1.0.0 }\npaths: {}\n',
      entry: { pipeline: { testing: { mocks: 'schema-faker' } } },
    });
    await expect(generateTestingLib(resolveClient(root, 'generated/empty-client'), root)).rejects.toThrow(
      'libs/generated/empty-client/openapi.yaml: no operations, no msw handlers',
    );
    addClient(root, 'generated/empty-orval-client', {
      spec: 'openapi: 3.0.3\ninfo: { title: Empty, version: 1.0.0 }\npaths: {}\n',
      entry: { pipeline: { testing: { mocks: 'orval' } } },
    });
    await expect(generateTestingLib(resolveClient(root, 'generated/empty-orval-client'), root)).rejects.toThrow(
      'orval produced no msw handlers',
    );
  });

  it('a spec without servers gets baseUrl ""', async () => {
    addClient(root, 'booking/generated/ping-client', { spec: fixture('no-models.yaml').replace(/servers:\n.*\n/, '') });
    const result = await generateTestingLib(resolveClient(root, 'booking/generated/ping-client'), root);
    expect(result.baseUrl).toBe('');
    expect(read(root, 'libs/booking/generated/ping-client/testing/src/generated/http.ts')).toContain(
      'export const pingClientBaseUrl = "";',
    );
  });
});
