/**
 * Workspace settings of the OpenAPI tooling: openapi-clients.json → `settings` (all optional, the defaults are the
 * values of the workspace this package comes from). Read at run time by executors, plugin and generator, and a
 * `json` input (field `settings`) of every generate target — a change invalidates exactly the generated code.
 *
 * Why openapi-clients.json and not nx.json plugin options: executors, the generator and verify read them at run
 * time (they never see plugin options), and every nx.json change invalidates the whole cache. Plugin options only
 * hold what shapes the graph alone: the target names (src/plugin/openapi-clients.ts).
 */

export type ToolingInputs = 'auto' | 'source' | 'package' | 'none';

export interface HeaderSettings {
  /** first lines of every generated file (lint directives) */
  lint: string[];
  /** last header line, placeholders `{source}` (`adapter <id>` | `testing`) and `{spec}` (workspace-relative spec) */
  banner: string;
}

/**
 * Experimental features, off by default (opt-in per workspace). A client using a disabled feature fails its
 * generate target with a hint and verify reports it — never silently ignored.
 */
export interface FeatureFlags {
  /** pipeline.overlays (OpenAPI Overlay 1.0, JSONPath subset) */
  overlays: boolean;
}

/** Mocks engine of the testing preset: `schema-faker` (default, own generator) or `orval` (deprecated, removed next iteration). */
export type MockEngine = 'schema-faker' | 'orval';
export const MOCK_ENGINES: readonly MockEngine[] = ['schema-faker', 'orval'];

export interface TestingSettings {
  /** workspace default, a client overrides it with pipeline.testing: { mocks } */
  mocks: MockEngine;
}

export interface OpenApiSettings {
  /** folder of all libs, client paths are relative to it */
  libsDir: string;
  /** reserved folder in a client path: `<clientFolder>/<name>` (shared) or `<domain>/<clientFolder>/<name>` */
  clientFolder: string;
  /** gitignored subfolder of `src/` every client lib re-exports (`export * from './<outputDir>'`) */
  outputDir: string;
  /** import alias prefix: `<aliasPrefix><client path>/<part>` */
  aliasPrefix: string;
  /** scope of the clients below `<libsDir>/<clientFolder>` */
  sharedScope: string;
  /** committed spec in the client folder, exactly one of them */
  specFiles: string[];
  /** tags of the client project, placeholder `{scope}` */
  clientTags: string[];
  /** tags of the part libs (built-in scaffold only), placeholders `{scope}`, `{layer}` */
  partTags: string[];
  header: HeaderSettings;
  /**
   * Lib scaffold of the client generator (config files of a part lib + its import path): module specifier
   * (workspace path or package), default: the built-in one (project.json + tsconfig.json + paths).
   */
  scaffold?: string;
  /**
   * How the tooling itself becomes a cache input of the generate targets: `source` = globs of its source folder
   * (package inside the workspace), `package` = externalDependencies on the npm package, `none`, `auto` = by location.
   */
  toolingInputs: ToolingInputs;
  features: FeatureFlags;
  testing: TestingSettings;
}

export const DEFAULT_SETTINGS: OpenApiSettings = {
  libsDir: 'libs',
  clientFolder: 'generated',
  outputDir: 'generated',
  aliasPrefix: '@mo-transfer/',
  sharedScope: 'shared',
  specFiles: ['openapi.yaml', 'openapi.json'],
  clientTags: ['scope:{scope}', 'generated'],
  partTags: ['scope:{scope}', 'type:{layer}', 'feat:none', 'generated'],
  header: {
    lint: ['/* eslint-disable */', '/* eslint-enable @nx/enforce-module-boundaries, no-restricted-imports */'],
    banner: '// Generated by @mo-transfer/tooling (openapi, {source}) from {spec}. Do not edit, do not commit.',
  },
  toolingInputs: 'auto',
  features: { overlays: false },
  testing: { mocks: 'schema-faker' },
};

/** A relative posix path without `.`/`..` segments: stays inside the workspace. */
export const isSafeRelativePath = (path: unknown): path is string =>
  typeof path === 'string' &&
  path.length > 0 &&
  !path.startsWith('/') &&
  !/^[A-Za-z]:/.test(path) &&
  !path.includes('\\') &&
  path.split('/').every((segment) => segment !== '' && segment !== '.' && segment !== '..');

const isStringList = (value: unknown): value is string[] => Array.isArray(value) && value.every((item) => typeof item === 'string');

/**
 * Violations of the settings — they become paths (libsDir, clientFolder, outputDir, specFiles; the pipeline deletes
 * <part>/src/<outputDir> before writing), so nothing may point outside the workspace or the part's src/.
 */
export function settingsProblems(settings: OpenApiSettings): string[] {
  const problems: string[] = [];
  if (!isSafeRelativePath(settings.libsDir)) problems.push('settings.libsDir: must be a relative path inside the workspace');
  for (const key of ['clientFolder', 'outputDir', 'sharedScope'] as const) {
    if (typeof settings[key] !== 'string' || !KEBAB_CASE.test(settings[key])) problems.push(`settings.${key}: must be one kebab-case folder name`);
  }
  if (!isStringList(settings.specFiles) || !settings.specFiles.length || !settings.specFiles.every((file) => /^[\w-]+(\.[\w-]+)+$/.test(file))) {
    problems.push('settings.specFiles: plain file names only');
  }
  if (typeof settings.aliasPrefix !== 'string') problems.push('settings.aliasPrefix: must be a string');
  for (const key of ['clientTags', 'partTags'] as const) if (!isStringList(settings[key])) problems.push(`settings.${key}: must be a list of strings`);
  if (!isStringList(settings.header.lint) || typeof settings.header.banner !== 'string') problems.push('settings.header: lint (strings) + banner (string)');
  if (!['auto', 'source', 'package', 'none'].includes(settings.toolingInputs)) problems.push('settings.toolingInputs: auto | source | package | none');
  if (typeof settings.features.overlays !== 'boolean') problems.push('settings.features.overlays: must be a boolean');
  return problems;
}

/** Settings of a parsed openapi-clients.json: its `settings` over the defaults (`header` merged per field). Throws for invalid ones. */
export function resolveSettings(partial: Partial<OpenApiSettings> | undefined): OpenApiSettings {
  const settings = mergeSettings(partial);
  const problems = settingsProblems(settings);
  if (problems.length) throw new Error(`openapi-clients.json → ${problems.join('; ')}`);
  return settings;
}

function mergeSettings(partial: Partial<OpenApiSettings> | undefined): OpenApiSettings {
  return {
    ...DEFAULT_SETTINGS,
    ...partial,
    header: { ...DEFAULT_SETTINGS.header, ...partial?.header },
    features: { ...DEFAULT_SETTINGS.features, ...partial?.features },
    testing: { ...DEFAULT_SETTINGS.testing, ...partial?.testing },
  };
}

/** Parts of a client: code parts (adapter) + the testing lib (spec only). */
export type Part = 'types' | 'api' | 'core';
export type ClientPart = Part | 'testing';
export const PARTS: readonly Part[] = ['types', 'api', 'core'];
export const TESTING_PART = 'testing';
/** layer of a part lib (tags of the built-in scaffold): HTTP is the data-access layer's job */
export const PART_LAYERS: Record<ClientPart, string> = {
  types: 'types',
  api: 'data-access',
  core: 'data-access',
  testing: 'testing',
};

export type Placement = 'shared' | { domain: string };

export interface ClientLocation {
  /** client path below libsDir, e.g. `generated/pet-client`, `booking/generated/booking-client` */
  path: string;
  /** folder name, e.g. `pet-client` */
  name: string;
  scope: string;
  placement: Placement;
}

/** `<clientFolder>/<name>` or `<domain>/<clientFolder>/<name>`; undefined for any other shape. */
export function parseClientPath(clientPath: string, settings: OpenApiSettings = DEFAULT_SETTINGS): ClientLocation | undefined {
  const segments = clientPath.split('/');
  if (!segments.every((segment) => KEBAB_CASE.test(segment))) return undefined;
  const shared = segments.length === 2 && segments[0] === settings.clientFolder;
  const domain = segments.length === 3 && segments[1] === settings.clientFolder && segments[0] !== settings.clientFolder;
  const name = segments.at(-1) ?? '';
  if ((!shared && !domain) || !name || name === settings.clientFolder) return undefined;
  return shared
    ? { path: clientPath, name, scope: settings.sharedScope, placement: 'shared' }
    : { path: clientPath, name, scope: segments[0], placement: { domain: segments[0] } };
}

/** Nx project name of a path below libsDir: `/` → `-` (the convention every part lib follows). */
export const projectNameFor = (path: string): string => path.replaceAll('/', '-');
export const clientRoot = (settings: OpenApiSettings, clientPath: string): string => `${settings.libsDir}/${clientPath}`;
export const partRoot = (settings: OpenApiSettings, clientPath: string, part: ClientPart): string =>
  `${clientRoot(settings, clientPath)}/${part}`;
export const partAlias = (settings: OpenApiSettings, clientPath: string, part: ClientPart): string =>
  `${settings.aliasPrefix}${clientPath}/${part}`;
/** `{scope}`-style placeholders */
export const fillTemplate = (template: string, values: Record<string, string>): string =>
  template.replace(/\{(\w+)\}/g, (match, key: string) => values[key] ?? match);

/** Header of every generated file: lint directives + banner (source, spec). */
export function generatedHeader(settings: OpenApiSettings, source: string, specFile: string): string {
  return [...settings.header.lint, fillTemplate(settings.header.banner, { source, spec: specFile }), ''].join('\n');
}

/** `pet-client` → `petClient` (prefix of the generated testing exports: petClientHttp, petClientHandlers …) */
export const camelCase = (name: string): string => name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());

/** kebab-case: client and domain folder names */
export const KEBAB_CASE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
